backend:
  name: git-gateway # Adjust based on your backend
  branch: main # Default GitHub branch

media_folder: static/img # Adjust if your media path differs
public_folder: /img # Adjust according to media_folder

collections:
  - name: "pages" # A name for your collection
    label: "Pages" # A label for your collection
    files:
      - file: "content/index.md" # Path to your Markdown file
        label: "Homepage"
        name: "homepage"
        fields: # Define the fields you want to be editable
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          # Add more fields as needed
